// File generated by FlutterFire CLI. Replace this file by running:
//   dart run flutterfire configure
// to connect your app to a Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Placeholder values — run `dart run flutterfire configure` to replace.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZCtkCsOYpreEn44HelvLxvkD1bWA_Vg',
    appId: '1:601312951370:web:a2298598379d85ba85bab3',
    messagingSenderId: '601312951370',
    projectId: 'henzo-79a1e',
    authDomain: 'henzo-79a1e.firebaseapp.com',
    storageBucket: 'henzo-79a1e.firebasestorage.app',
    measurementId: 'G-0D5TCGWQH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1KjbncEMpzPl5YbqHCIPvkpEJjVBEQ4',
    appId: '1:601312951370:android:f6dfff2ead95cff285bab3',
    messagingSenderId: '601312951370',
    projectId: 'henzo-79a1e',
    storageBucket: 'henzo-79a1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDocvyhRMnlD5sZYME89d9SoZDkKwXAJ6M',
    appId: '1:601312951370:ios:c4793a94de2137fa85bab3',
    messagingSenderId: '601312951370',
    projectId: 'henzo-79a1e',
    storageBucket: 'henzo-79a1e.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDocvyhRMnlD5sZYME89d9SoZDkKwXAJ6M',
    appId: '1:601312951370:ios:c4793a94de2137fa85bab3',
    messagingSenderId: '601312951370',
    projectId: 'henzo-79a1e',
    storageBucket: 'henzo-79a1e.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZCtkCsOYpreEn44HelvLxvkD1bWA_Vg',
    appId: '1:601312951370:web:4c2ab692b0ef286785bab3',
    messagingSenderId: '601312951370',
    projectId: 'henzo-79a1e',
    authDomain: 'henzo-79a1e.firebaseapp.com',
    storageBucket: 'henzo-79a1e.firebasestorage.app',
    measurementId: 'G-ZPW16J3GYD',
  );
}
